dist: trusty

language: go

go:
    - 1.8.x
    - 1.9
    - tip

before_script:
  - echo $HOSTNAME
  - mkdir -p $GOPATH/bin
  - wget --version
  - wget https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/0.8.1/vault_0.8.1_linux_amd64.zip
  - unzip -d $GOPATH/bin consul_0.9.2_linux_amd64.zip
  - unzip -d $GOPATH/bin vault_0.8.1_linux_amd64.zip
  - vault --version
  - consul --version
