dist: bioinic
sudo: false
language: go

go:
  - 1.15
  - master

addons:
  hosts:
    - example.com
    - example2.com

script: make travis

jobs:
  include:
    - stage: deploy pages
      script: make travis-pages
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs/public
        target_branch: gh-pages
        fqdn: fabiolb.net
        on:
          branch: master
