dist: trusty

language: go

go:
    - 1.7.4
    - 1.8rc3

before_script:
  - echo $HOSTNAME
  - mkdir -p $GOPATH/bin
  - wget --version
  - wget https://releases.hashicorp.com/consul/0.7.2/consul_0.7.2_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/0.6.4/vault_0.6.4_linux_amd64.zip
  - unzip -d $GOPATH/bin consul_0.7.2_linux_amd64.zip
  - unzip -d $GOPATH/bin vault_0.6.4_linux_amd64.zip
  - vault --version
  - consul --version
